### PR TITLE
Feature/channel

### PR DESCRIPTION
**Pull request by sebamiro**
Init of Join function, added a lot of things needed with tests

### CODE REVIEW

**Review by fletcher97 — CHANGES_REQUESTED** [review]
Attributes should come before functions (Channel.hpp:24)
All Pre-compiler instructions (except include) should be in a header. Also defines should have a more recognizable name  (Channel.cpp:5)
References (and sometimes pointers) are used not only but also to save memory. Creating a reference to a char would use more memory and make no sence imho (Channell.coo:116)
Templates should specify their types (Channel.cpp:141 Possibly other places too)
Tests should test multiple value, especially error/forbiden value (i.e. forbiden chars in setname) (ChannelUT.cpp:43)

**Review by fletcher97 — COMMENTED** [review]
Tests don't compile... ChannelUT.cpp:
* L95: `no member named 'banClient' in 'ft_irc::ChannelUT'`
* L96: `no member named 'banClient' in 'ft_irc::ChannelUT'`
* L97: `no member named '_banned' in 'ft_irc::ChannelUT'`
* L105: `no member named '_invited' in 'ft_irc::ChannelUT'`
* L149: `no member named 'banClient' in 'ft_irc::ChannelUT'`
* L151: `no member named '_banned' in 'ft_irc::ChannelUT'`

Are you using the hook? It should prevent this.....

**Comment by sebamiro** [comment]
No I forget to put the hook, but it compiles fine to me, I just had problem in a logging, but I dont have that errors

**Comment by fletcher97** [comment]
Probably linux? But I doubt it. Running `make compile-test` doesn't give you any errors?
Maybe you have extra changes that weren't pushed?

**Comment by sebamiro** [comment]
No there are no errors, and if I look for these words in that file there are no matches. I think I pushed everything, but maybe I am wrong, today I am not coming to the campus so tomorrow I'll check it

**Comment by fletcher97** [comment]
You are correct. The mistake was on my end. I'll review the code again. Sorry

**Review by fletcher97 — APPROVED** [review]
Looks fine

**Review by gemartin99 — APPROVED** [review]

**Pull request merged**
