### PR TITLE
Feature/flt update

### PR DESCRIPTION
**Pull request by fletcher97**
Updated libflt and changed makefile for it to compile properly

### CODE REVIEW

**Comment by sebamiro** [comment]
Why are these comments in libflt/tst/main.cpp

**Comment by fletcher97** [comment]
I'm going to rewrite all tests in a proper way. I started with log and will be adding more for the different parts. As I wanted to speedup a bit I added the libflt as is on it's current branch. When I get time to update and write the tests I'll clean the main a bit.

**Review by sebamiro — APPROVED** [review]
Its, fine. Let's speed things up a bit

**Comment by fletcher97** [comment]
Added Workflow to check Code style and that it compiles both on linux and iMac. And that it passes tests both on linux and iMac. This branch will fail the coverage as no tests where added.

**Review by gemartin99 — APPROVED** [review]

**Pull request merged**
